# Generated by Django 3.2 on 2022-02-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=100)),
                ('coin_symbol', models.CharField(max_length=10)),
                ('coin_image', models.ImageField(default='coin_images/default.png', upload_to='coin_images/')),
            ],
        ),
    ]
