# Generated by Django 3.2 on 2022-02-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_tradingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingOrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_order_type_name', models.CharField(max_length=100)),
                ('trading_order_type_symbol', models.CharField(max_length=50)),
            ],
        ),
    ]
