# Generated by Django 3.2 on 2022-02-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profiledirectorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_quantity', models.CharField(max_length=100)),
                ('target_quantity', models.CharField(max_length=100)),
                ('first_trading_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_profile_trading_coin', to='profiles.marketcoins')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('second_trading_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_profile_trading_coin', to='profiles.marketcoins')),
                ('trading_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tradingstatus')),
                ('trading_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tradingtype')),
            ],
        ),
    ]
