# Generated by Django 3.2 on 2022-03-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profiletradingorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledirectorder',
            name='limit_order_quantity',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
