# Generated by Django 3.2 on 2022-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profiletrading_trading_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletrading',
            name='trading_status',
            field=models.CharField(choices=[('0', 'RUN'), ('1', 'COMPLETE'), ('3', 'STOP')], default=0, max_length=2),
        ),
    ]
