# Generated by Django 3.2 on 2022-03-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profiletrading_trading_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticTradingCOinsMarketValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_coin_market_value', models.CharField(max_length=100)),
                ('second_coin_market_value', models.CharField(max_length=100)),
                ('trading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiletrading')),
            ],
        ),
    ]
