# Generated by Django 3.2 on 2022-03-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_automatictradingcoinsmarketvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatictradingcoinsmarketvalues',
            name='market_close',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='automatictradingcoinsmarketvalues',
            name='market_high',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='automatictradingcoinsmarketvalues',
            name='market_low',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='automatictradingcoinsmarketvalues',
            name='market_open',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
