# Generated by Django 3.2 on 2022-03-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20220311_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcoins',
            name='trading_factor',
            field=models.CharField(default='0.01', max_length=10),
        ),
    ]
